export const FormDataServiceLocation = {
  formData: {
    projectId: "",
    department: "",
    subDeprtmt: "",
    projectName: "",
    brand: "",
    generatedDate: "",
    fromDate: "",
    toDate: "",
    agrmntNumber: "",
    ordrNumber: "",
    respPersonal: "",
    srvcProvider: "",
    srvcReceiver: "",
    prjctDesc: "",
    mngrName: "",
    clientName: "",
    justification: "",
    location: "",
    levelInfo: [],
    srvcCost: "",
    srvcMonthlyCost: "",
    srvcRemainBdgt: "",
    miscCost: "",
    miscPricing: "",
    miscMonthlyBdgt: "",
    miscRemainBdgt: "",
    totalCost: "",
    totalMonthlyBdgt: "",
    totalRemainBdgt: "",
    costDetails: {
      srvcCost: "",
      srvcMonthlyCost: "",
      srvcRemainBdgt: "",
      miscCost: "",
      miscPricing: "",
      miscMonthlyBdgt: "",
      miscRemainBdgt: "",
      totalCost: "",
      totalMonthlyBdgt: "",
      totalRemainBdgt: "",
    },
  },
  getFormData: function () {
    return this.formData;
  },
};

export default FormDataServiceLocation;
